# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:9

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - name: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    alias: elasticsearch

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - mushrooms/node_modules/
  - books/node_modules/
  - ui/node_modules/

stages:
  - compile
#  - package

mushrooms:
  stage: compile
  script:
   - cd mushrooms
   - npm install
   - npm run build

books:
  stage: compile
  script:
    - cd books
    - npm install
    - npm run build

ui:
  stage: compile
  script:
    - cd ui
    - npm install
    - npm run build