cache:
  paths:
  - mushrooms/node_modules/
  - books/node_modules/
  - ui/node_modules/

stages:
  - compile
#  - package

mushrooms:
  stage: compile
  image: node:11
  script:
   - cd mushrooms
   - npm install
   - npm run build

books:
  stage: compile
  image: node:11
  script:
    - cd books
    - npm install
    - npm run build

ui:
  stage: compile
  image: node:11
  script:
    - cd ui
    - npm install
    - npm run build