environment:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

cache:
  paths:
  - mushrooms/node_modules/
  - books/node_modules/
  - ui/node_modules/

stages:
  - compile
  - dockerize

mushrooms:
  stage: compile
  image: node:11
  script:
   - cd mushrooms
   - npm install
   - npm run build
books:
  stage: compile
  image: node:11
  script:
    - cd books
    - npm install
    - npm run build

ui:
  stage: compile
  image: node:11
  script:
    - cd ui
    - npm install
    - npm run build

dockerize:
  stage: dockerize
  image: docker:stable
  script:
    - docker build -t registry.gitlab.com/piotrjanik/opa-demo-mushrooms mushrooms
    - docker build -t registry.gitlab.com/piotrjanik/opa-demo-books books
    - docker build -t registry.gitlab.com/piotrjanik/opa-demo-ui ui
    - docker push registry.gitlab.com/piotrjanik/opa-demo-mushrooms
    - docker push registry.gitlab.com/piotrjanik/opa-demo-books
    - docker push registry.gitlab.com/piotrjanik/opa-demo-ui