cache:
  paths:
  - mushrooms/node_modules/
  - books/node_modules/
  - ui/node_modules/

stages:
  - compile
  - dockerize

mushrooms:
  stage: compile
  image: node:11
  script:
   - cd mushrooms
   - npm install
   - npm run build
  artifacts:
    paths:
      - mushrooms/out/
books:
  stage: compile
  image: node:11
  script:
    - cd books
    - npm install
    - npm run build
  artifacts:
    paths:
      - books/out/

ui:
  stage: compile
  image: node:11
  script:
    - cd ui
    - npm install
    - npm run build
  artifacts:
    paths:
      - ui/dist/

#opa:
#  stage: compile
#  image:
#    name: openpolicyagent/opa
#    command: ["test","./demo"]

dockerize:
  tags:
    - docker
  stage: dockerize
  image: docker:stable
  dependencies:
    - mushrooms
    - books
    - ui
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/piotrjanik/opa-smurf/opa-demo-mushrooms mushrooms
    - docker build -t registry.gitlab.com/piotrjanik/opa-smurf/opa-demo-books books
    - docker build -t registry.gitlab.com/piotrjanik/opa-smurf/opa-demo-ui ui
    - docker build -t registry.gitlab.com/piotrjanik/opa-smurf/opa-demo-policies opa
    - docker push registry.gitlab.com/piotrjanik/opa-smurf/opa-demo-mushrooms
    - docker push registry.gitlab.com/piotrjanik/opa-smurf/opa-demo-books
    - docker push registry.gitlab.com/piotrjanik/opa-smurf/opa-demo-ui
    - docker push registry.gitlab.com/piotrjanik/opa-smurf/opa-demo-policies